### ISSUE TITLE
Failed to load plugin insomnia-plugin-load-test-timing-master

### ISSUE THREAD

**Issue by mrturbo-750** [shindig/insomnia-plugin-load-test-timing#10]
When insomnia is trying to load insomnia-plugin-load-test-timing-master it throws the following error:

Thanks for all your hard work on this plugin and any help is highly appreciated! 

Error: Cannot find module 'electron-progressbar'
Require stack:
- C:\Users\rj9762\AppData\Roaming\Insomnia\plugins\insomnia-plugin-load-test-timing-master\load-test-timing.js
- C:\Users\rj9762\AppData\Local\insomnia\app-2021.7.2\resources\app.asar\renderer.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.o._resolveFilename (electron/js2c/renderer_init.js:35:917)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\rj9762\AppData\Roaming\Insomnia\plugins\insomnia-plugin-load-test-timing-master\load-test-timing.js:4:21)
    at Object.<anonymous> (C:\Users\rj9762\AppData\Roaming\Insomnia\plugins\insomnia-plugin-load-test-timing-master\load-test-timing.js:248:3)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)

**Comment by xlith** [comment]
Thanks for the kind words. 

There may be two things:

1. The folder name should have been `insomnia-plugin-load-test-timing`. I'm not sure why it's `insomnia-plugin-load-test-timing-master`. So how did you install the plugin? Maybe there is something wrong with the installation. 
2. It's in a Windows environment so maybe the problem is related to the environment. I'm not sure.

**Comment by chrillep** [comment]
having similar issue on macos obscured my user with **`<USER>`**
```js
TypeError: Cannot read properties of undefined (reading 'BrowserWindow')
    at Object.<anonymous> (/Users/<USER>/Library/Application Support/Insomnia/plugins/insomnia-plugin-load-test-timing/load-test-timing.js:2:13)
    at Object.<anonymous> (/Users/<USER>/Library/Application Support/Insomnia/plugins/insomnia-plugin-load-test-timing/load-test-timing.js:248:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by verheyenkoen** [comment]
@chrillep Same error.

**Comment by panos-stavrianos** [comment]
@chrillep Same on Ubuntu 20.04

**Comment by chrillep** [comment]
@xlith @shindig ping :)

**Comment by xlith** [comment]
Sorry, everyone I didn't have the opportunity to fix this. I'll try to do it now. 

TBH, I don't have much experience with electron apps.  If I interpreted the docs correctly, the bad thing is it seems electron has removed access to some elements that we use in this plugin so in order to make it work again I'll have to make the output much simpler. 
No, new browser window, no progress bar, etc.  
I'll push the changes as soon as I can.

**Comment by xlith** [comment]
I think this should be sufficient. @shindig can you please help with the review and new version release?
